### ISSUE TITLE
I got this error when I start test "This is the first app"

### ISSUE THREAD

**Issue by AhmedMensh** [HouseArgent/speed_test#1]

**Comment by david-macharia** [comment]
Did you get it while running the example code in the package ? Please provide a minimum  issue to reproduce the issue

**Comment by AhmedMensh** [comment]
Actually it works fine my bad I had an internet connection problem.
Thank you for your response

**Comment by AhmedMensh** [comment]
Hi dear
I want to thank you for your plugin to save me a lot of time
I have one question do you have any idea how to calculate data used in
download and upload?
Regards
